### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by DyroS3** [antond15/gfx-font-converter#3]
![image](https://github.com/antond15/gfx-font-converter/assets/64310374/f64bfec5-b128-40ff-a52f-45eceda160bd)

**Comment by antond15** [comment]
Looks like you are out of memory 🤯

Provide some context, information, reproduction steps, etc.
Not just a screenshot of 50 lines saying the same thing.

**Comment by DyroS3** [comment]
Oh! Sorry, I just uploaded the fonts I need to debug.
I found this error when converting some fonts
For example this font: 
https://fonts.google.com/noto/specimen/Noto+Sans+SC?subset=chinese-simplified&noto.script=Hans
